# Generated by Django 3.2.3 on 2021-11-21 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_New_Expenses',
            fields=[
                ('Eid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Purpose', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(default=datetime.datetime(2021, 11, 21, 18, 3, 12, 685658), verbose_name='date published')),
            ],
        ),
    ]
