# Generated by Django 3.2.3 on 2021-11-21 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 18, 6, 38, 724846), verbose_name='date published'),
        ),
    ]
