# Generated by Django 3.2.3 on 2021-11-21 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0002_alter_add_new_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 18, 9, 41, 264017), verbose_name='date published'),
        ),
    ]
