# Generated by Django 3.2.3 on 2021-11-21 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0003_alter_add_new_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 23, 23, 37, 708244), verbose_name='date published'),
        ),
    ]
