# Generated by Django 3.2.3 on 2021-11-22 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0005_alter_add_new_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 11, 53, 50, 655988), verbose_name='date published'),
        ),
    ]
