# Generated by Django 3.2.3 on 2021-11-24 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0006_alter_add_new_expenses_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_new_member',
            fields=[
                ('Mid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Mobileno', models.IntegerField(max_length=10)),
                ('Work', models.CharField(max_length=20)),
                ('Income', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 22, 10, 5, 607270), verbose_name='date published'),
        ),
    ]
