# Generated by Django 3.2.3 on 2021-11-24 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0007_auto_20211124_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 22, 26, 30, 729103), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='add_new_member',
            name='Mobileno',
            field=models.IntegerField(max_length=20),
        ),
    ]
