# Generated by Django 3.2.3 on 2021-11-24 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0009_auto_20211124_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 22, 29, 26, 950532), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='add_new_member',
            name='Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_new_member',
            name='Mobile_no',
            field=models.IntegerField(),
        ),
    ]
