# Generated by Django 3.2.3 on 2021-11-24 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0010_auto_20211124_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 22, 40, 21, 779472), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='add_new_member',
            name='Mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
