# Generated by Django 3.2.9 on 2021-11-26 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetapp', '0011_auto_20211124_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_expenses',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 17, 18, 15, 421976), verbose_name='date published'),
        ),
    ]
